
/**
 * Xavier Porter
 *  602 Intermediate Software Development.
 *  2/25/20
 *  
 *  Program: You have been hired by CarsAndCars to write a Car payment calculator application. 
        The UI mockups are getting done by the customer and you are required to follow the requirements once they are complete.
        However, the decision has not yet been made if this application will be a desktop application, a web application, or a mobile application.
        What you know is that back-end business logic needs to be implemented using latest java and should be able to be called by any driver application.
        This UI receives three inputs from the user and calculates the fourth. Clear buttons are added 
        to clear the text in the fields to allow newer inputs to be entered. An exit button was added to 
        terminate the program. 
 * 
 */



import javax.swing.JOptionPane;

public class Calculator extends javax.swing.JFrame {

    //Create calculator object
    FinanceCalculator calculator = new FinanceCalculator();
    
    //Declare instance variables
    private double loanAmount;
    private int numberOfPayments;
    private float annualInterestRate;
    private double paymentAmount;
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Finance Calculator");

        jTextField1.setName("loanAmount"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Loan Amount:");

        jLabel2.setText("Number of Payments: ");

        jLabel3.setText("Annual Interest Rate:(%) ");

        jLabel4.setText("Payment Amount:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField3PropertyChange(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        calculate.setBackground(new java.awt.Color(255, 255, 153));
        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(calculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculate)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Text field for Loan Amount
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
      
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    //Text field for Number of payments
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed


    }//GEN-LAST:event_jTextField2ActionPerformed

    //Text field for annual interest rate
    private void jTextField3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField3PropertyChange

     

    }//GEN-LAST:event_jTextField3PropertyChange


    //Text field for payment amount
    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed


    }//GEN-LAST:event_jTextField4ActionPerformed

    //When the calculate button is selected. 
    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
       
        //First define variables
        double loanAmount, paymentAmount, result;
        float annualInterestRate;
        int numberOfPayments;
        

             //If the user doesn't enter text for the loanAmount textfield
             if(jTextField1.getText().length() == 0){
            
             //parse variables to calculate loanAmount and set within method
             annualInterestRate = Float.parseFloat(jTextField3.getText());
             numberOfPayments = Integer.parseInt(jTextField2.getText());
             paymentAmount = Double.parseDouble(jTextField4.getText());
             

             //If the user enters a negative Annual interest rate display a message. 
             if(annualInterestRate < 0 || numberOfPayments <= 2 || numberOfPayments > 72 || paymentAmount <= 0){
            JOptionPane.showMessageDialog(this, "invalid input, try again");
             }
                   
             
             else {
                //invoke method to calculate loanAmount
                loanAmount = calculator.calculate(numberOfPayments, annualInterestRate, paymentAmount);
      
                //display result in the textfield
                this.jTextField1.setText(String.format("%.2f",loanAmount));

             }
                
             
            }
             
             //If the user doesn't enter text for the number of payments textfield
             else if(jTextField2.getText().length() == 0){
                 
                 loanAmount = Double.parseDouble(jTextField1.getText());
                 annualInterestRate = Float.parseFloat(jTextField3.getText());
                 paymentAmount = Double.parseDouble(jTextField4.getText());

                 //If the user enters a negative Annual interest rate or payment amount less than 0.
                 if(annualInterestRate < 0 || paymentAmount <= 0){
                  JOptionPane.showMessageDialog(this, "invalid input, try again");
                  }
                 
                else{
                numberOfPayments = calculator.calculate(annualInterestRate, loanAmount, paymentAmount);

                jTextField2.setText(String.valueOf(numberOfPayments));
                }
             }
             
             //If the user doesn't enter a value for annual interest rate
             else if(jTextField3.getText().length() == 0){
                loanAmount = Double.parseDouble(jTextField1.getText());
                numberOfPayments = Integer.parseInt(jTextField2.getText());
                paymentAmount = Double.parseDouble(jTextField4.getText());

                
                //If the user enters a negative Annual interest rate display a message. 
                if(paymentAmount <= 0 || numberOfPayments <= 2 || numberOfPayments > 72){
                JOptionPane.showMessageDialog(this, "invalid input, try again");
                }
             
                else{
                annualInterestRate = calculator.calculate(loanAmount, numberOfPayments, paymentAmount);
                
                jTextField3.setText(String.format("%.2f", annualInterestRate));
                
                }

             }
             
             //If the user doesn't enter a value for payment amount
             else if(jTextField4.getText().length() == 0){
                 
                 loanAmount = Double.parseDouble(jTextField1.getText());
                 numberOfPayments = Integer.parseInt(jTextField2.getText());
                 annualInterestRate = Float.parseFloat(jTextField3.getText());
                 
                 
                //If the user enters an invalid input
                if(annualInterestRate < 0 || numberOfPayments <= 2 || numberOfPayments > 72){
                JOptionPane.showMessageDialog(this, "invalid input, try again");
                }
                
                else{ 

                paymentAmount = calculator.calculate(annualInterestRate, loanAmount, numberOfPayments);

                 jTextField4.setText(String.format("%.2f", paymentAmount));
                }
             }


              

 
        
    }//GEN-LAST:event_calculateActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed

 
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
     //Clear the jTextfields to allow new inputs to be entered
     jTextField1.setText("");
     jTextField2.setText("");
     jTextField3.setText("");
     jTextField4.setText("");


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
      //Exit the calculator
      System.exit(0);


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
